# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    self.driver.get("https://prerelease.smarttrader.com/")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.CSS_SELECTOR, ".landing-header__navigation > .landing-header__nav-link:nth-child(1)").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".ucpicon-trading-b").click()
    self.driver.find_element(By.LINK_TEXT, "Manage Accounts").click()
    self.driver.find_element(By.ID, "addAccountBtn").click()
    element = self.driver.find_element(By.ID, "addAccountBtn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "BrokerConnectionSettingsDialog").click()
    self.driver.find_element(By.ID, "manageAccountsDialog").click()
  
